### ISSUE TITLE
1. Character Selection Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#1]
1- As a player, so that I can create a character, I want a character selection screen.

**Comment by changmj4** [comment]
1- As a player, so that I can create a character, I want a character selection screen.

**Comment by changmj4** [comment]
Given I am on the start screen of the game
When I click on "New Game"
Then I should be on a new screen allowing me to create a character

**Comment by martinda3** [comment]
Given I am on the start screen of the game
When I click on "Load Game"
Then I should be on a new screen allowing me to choose a previously made character

**Comment by martinda3** [comment]
Given I am on the charter create screen,
When i look at the screen i should have different customization options
Then i can have options of customization

**Comment by McDermottSJ** [comment]
Given in game dialog
When NPC's address my character,
Then the game should address me by my choose name.

**Comment by McDermottSJ** [comment]
Given I have chosen a character,
When my character is loaded,
Then the character should have the correct stats
