### ISSUE TITLE
10. Ending Fight Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#10]
10- As a player, so that I can be motivated to engage in fights, I want to get rewards out of winning fights and risks if I lose them.

**Comment by McDermottSJ** [comment]
*Given* I am in combat with an enemy,
*When* I defeat the enemy,
*Then* I want to gain experience or items

**Comment by McDermottSJ** [comment]
*Given* I am in combat with an enemy,
*When* I am beaten by the enemy,
*Then* I want to lose my previous rewards.

**Comment by McDermottSJ** [comment]
*Given* I am in combat with an enemy,
*When* I defeat a larger enemy,
*Then* I want to gain better rewards (experience and/or items)
