### ISSUE TITLE
3. Combat Screen Story

### ISSUE THREAD

**Issue by McDermottSJ** [vcu-cmsc355-f17/android-app-mads#11]
As a player, so that I can choose my strategy, I want a combat screen.

**Comment by changmj4** [comment]
Given I am exploring the world
When I encounter an enemy
Then a new screen should show up giving me new options for combat

**Comment by changmj4** [comment]
Given I am in the combat screen
When I want to choose a strategy
Then I should be given options for attack, utility, and escape

**Comment by changmj4** [comment]
Given I am in the middle of the fight
When I want to know who wins the fight
Then either the enemy or my hp should be depleted.
