### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#2]
2- As a player, so that I can name my character, I want a naming option.

**Comment by changmj4** [comment]
Given I'm on the character selection screen
When I type my character's name in the username box
And click create
Then I should have a new character with selected name

**Comment by martinda3** [comment]
Given the option to confirm my name
When I click on "Confirm"
Then my choose name will appear above my character.

**Comment by martinda3** [comment]
Given in game dialog
When NPC's address my character,
Then the game should address me by my choose name.
