### ISSUE TITLE
4. World Creation Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#4]
4- As a player, so that I can have an adventure, I want to have a world.

**Comment by mandy1339** [comment]
Given that I clicked start new game
When the screen changes
My hero appears in a world.

**Comment by mandy1339** [comment]
Given that I clicked start new game
When the screen changes
My hero appears in a well designed world.

**Comment by mandy1339** [comment]
Given that I clicked start new game
When the screen changes
My hero appears in a world with obstacles and creatures.
