### ISSUE TITLE
5. User Controls Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#5]
5- As a player, so that I can interact with the world, I want controls.

**Comment by mandy1339** [comment]
Given that I have started or resumed a game
When I look at my game screen
Then I can see a button.

**Comment by mandy1339** [comment]
Given that I have started or resumed a game
When I look at my game screen
Then I can see different buttons.

**Comment by mandy1339** [comment]
Given that I have started or resumed a game
When I press a button
Then it has an effect in the game
