### ISSUE TITLE
6. Non-Player Units Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#6]
6- As a player, so that I can interact in different way, I want to have NPC's.

**Comment by mandy1339** [comment]
Given I am in a room
When I look round my character
Then I see non player entities

**Comment by mandy1339** [comment]
Given I am in a different room
When I look around my character
Then I see different non-player entities

**Comment by mandy1339** [comment]
Given I am in a room
When I walk up to a non-player entity
it reacts to my character.
