### ISSUE TITLE
7. Inventory Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#7]
7- As a player, so that I can hold items, I want an inventory system.

**Comment by McDermottSJ** [comment]
*Given* I am wandering the map,
*When* I enter a new area,
*Then* I want a chance to find new items

**Comment by McDermottSJ** [comment]
*Given* I am wandering the map,
*When* I am in a difficult area,
*Then* I want to find better items

**Comment by McDermottSJ** [comment]
*Given* I am wander the map
*When* I am low on health
*Then* I want to try and find a health boost
