### ISSUE TITLE
9. Fight Story

### ISSUE THREAD

**Issue by changmj4** [vcu-cmsc355-f17/android-app-mads#9]
9- As a player, so that I can get experience, I want to be able to fight.

**Comment by McDermottSJ** [comment]
*Given* I am walking in the map
*When* I encounter an npc
*Then* I want to engage in combat

**Comment by McDermottSJ** [comment]
*Given* I am in a fight,
*When* I win the fight,
*Then* I want to continue exploring the map

**Comment by McDermottSJ** [comment]
*Given* I am walking in the map,
*When* I enter a more difficult area,
*Then* I want to encounter more npcs
